# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 中華民國資訊管理學會 # 目前無用
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true       # Site-wide kill switch, disabled here it doesn't run at all
  debug: true         # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  collection: "posts" # The default document collection to paginate if nothing is specified ('posts' is default)
  per_page: 15         # How many objects per paginated page, used to be `paginate` (default: 0, means all)

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  title: ":title (第 :num 頁)"  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  limit: 0  # Limit how many pagenated pages to create (default: 0, means all)

  
  sort_field: "date"  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_reverse: true  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  category: "posts"   # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  tag: ""             # Optional, the default tag to use, omit to disable

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 1
    after: 1

############################################################

permalink: /news/:categories/:title

autoprefixer:
  browsers:
    - last 4 versions

itemList: 
- name: "高階13色流式細胞儀"
  manager: "莊幸恩"
  extension: "2371"
  image: "/assets/img/items/01.webp"
- name: "超導核磁共振儀"
  manager: "葛永和"
  extension: "2289"
  image: "/assets/img/items/02.webp"
- name: "電子顯微鏡"
  manager: "白家程"
  extension: "1234"
  image: "/assets/img/items/03.webp"
- name: "質譜儀"
  manager: "方威翔"
  extension: "5678"
  image: "/assets/img/items/04.webp"
- name: "核磁共振波譜儀"
  manager: "温子威"
  extension: "9101"
  image: "/assets/img/items/05.webp"
- name: "光譜儀"
  manager: "杜冠中"
  extension: "1213"
  image: "/assets/img/items/06.webp"
- name: "掃描電子顯微鏡"
  manager: "辜詩琳"
  extension: "1415"
  image: "/assets/img/items/07.webp"
- name: "X射線衍射儀"
  manager: "文俞廷"
  extension: "1617"
  image: "/assets/img/items/08.webp"
- name: "拉曼光譜儀"
  manager: "丁東昇"
  extension: "1819"
  image: "/assets/img/items/09.webp"
- name: "紅外光譜儀"
  manager: "涂健鴻"
  extension: "2021"
  image: "/assets/img/items/10.webp"
- name: "超高速離心機"
  manager: "李正偉"
  extension: "2223"
  image: "/assets/img/items/11.webp"
- name: "液相色譜儀"
  manager: "顏玟瑾"
  extension: "2425"
  image: "/assets/img/items/12.webp"
- name: "氣相色譜儀"
  manager: "熊愉萱"
  extension: "2627"
  image: "/assets/img/items/13.webp"
- name: "顆粒分析儀"
  manager: "歐美伊"
  extension: "2829"
  image: "/assets/img/items/14.webp"
- name: "分光光度計"
  manager: "翁勝翔"
  extension: "3031"
  image: "/assets/img/items/15.webp"
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
